sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: xjFfdki5qOiGIuL/9VCQ0+CGaScC1B5D+wsi+z+YVpE14iH6csTqGNv1tyVyPE3ZsNsXlzn5ndyIfUiXYVwO0wZCHBWq3QBfZZEKy76Nhh18IGK84IaoDIKb09GFseBFTD/wiiyuwPe3OOYKZQes1WEgmxezpEhYol5pO9e3hmYqmJsh2B9sMktj7VuxxXjfAN15nzteky+DpAkYCm79WBVdZFuSM6pRUPPLibio16ihqP23NGPg4N2pr2pNhsVrCTkgSK9fyto3xLu5BLGB7/5tJlhQIkws8MEorncjhCayTi3BhfGvOCMLZ8+F39a5FjNwJZzjpC3wQDA14V+yleoZ1pPt/AWSY+755yw4ss8AD2aAv9tTRXq4OUowVtbusymzVZlZNj/vD20zRVy4tX6q7Lb9tHsnVBKIeki70tPL4rDVa6M4tkz7D/drouJZFpmOHaCMhHGLSCk1HX9d/PSU/py4tS2+dsjiFqczt12GlIGCxlgist4HyDoEoD9NeDe0l3iQRtacWDb5y8hZ8//ijTkBi/NVvdcgpPtNHvwbZUUyDfGrnQzXtUiaJsgKYt3kIgUneWUNhU28DKx8wmtjY2gNKXGKzOB7mqd0mKz6WN7Qpy3fHqz390ozrDkK92BHlA5rjz0zvnvmHHTN3WLpBTzOURQAkO/BmsqLwT0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Pot-Boiler--A-Comedy-in-Four-Acts_5806
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy